project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto
  
website:
  title: "State Jobs Day"
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    search: true
    collapse: true
  
    right: 
      - icon: fab fa-github
        href: https://github.com/emmacohn/statejobsday_charts
        
#make sure all .qmd files are listed somewhere below

  sidebar: 
    style: 'docked'
    search: true
    collapse-level: 1
    contents:

    - text: "About"
      href: index.qmd

    - section: "Charts"
      contents:
      - nonfarm.qmd
      - urates.qmd
      - nonfarm2.qmd
    
format:
  html:
    theme: 
      #website theme includes dark and light modes!
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

editor: visual

